# yazi.toml
[mgr]
show_hidden = true
sort_by = "alphabetical"
sort_sensitive = true
sort_dir_first = true
line_mode = "size_and_permissions"
scroll_off = 4

[preview]
wrap = "no"
tab_size = 2

[input]
cursor_blink = false

[flavor]
use = "catppuccin-mocha"
# For upcoming Yazi 0.4 (nightly version):
dark = "catppuccin-mocha"

[opener]
edit = [{ run = 'neovide $@', desc = "Neovide", block = true, for = "unix" }]
